
replicas: 1 # for better debugging experience
controller:
  env:
    - name: FEATURE_GATES
      value: Drift=true
    - name: LEADER_ELECT # disable leader election for better debugging / troubleshooting experience
      value: "false"
    # disable HTTP/2 to reduce ARM throttling on large-scale tests;
    # with this in place write (and read) QPS can be increased too
    #- name: GODEBUG
    #  value: http2client=0
    # options
    - name: CLUSTER_NAME
      value: primary
    - name: CLUSTER_ENDPOINT
      value: https://primarydns-e4usdkv3.hcp.eastus.azmk8s.io:443
    - name: KUBELET_BOOTSTRAP_TOKEN
      value: jsngdw.60gncnagy2kzy4op
    - name: SSH_PUBLIC_KEY
      value: "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC7j2W0vhu2ENO6jg2t4+tBUddjCTuo/E8LTUeriF/EyzYpIBUdKUOLWrGKUJ9/07IfiyfNOfIU27D3R48SgRF83g5apDYue2AJZKx8DG312FGxnulFukk3L2ErHA0Gy+UPMA0iYpP8HH4cg9tKK8J6jwHXAwLMT+CImuR+gxCWrYZCOTR8HGjucYuhsLRxFk4JeItwMLoJ5nqPGru5P94BUrNQ/jK/08lzyksOb4lniSLsypAYG0dOTzTmPeVOCcllQmCVca8udIR1K+1Y+7XYwTWRmSuAQgj55aTuiBfGXC8BjvPd80LVdlnTZ8D+qNpINM+GDXzCu5xiXobA9Jdt5rGmj/G/aVdIJgS4fVusFcCTZC1Keb0w09IX2RznnompCgcI1piP4BERpS2N3yCUX00f2cOZcVes3fxb+FwcQuMCjwb4PdUJu8ZaWqr15pvpqXkNLx2Xdr9KnLxTrMIgC4kVl9+I/lVY9Md1PGqBrUL2eb2m8WBvlXfqf3Rf/zyXm/miJNvfeyiElACzR3EdD1ynSjEeNawmUmAwk/k1nh6pt7bHVq/zEHbB1FFvXVaKtuE0+tDNaqfuSiFSSnssAKxW/tbxy6nRg6m8Nf9ZHylQ1dFBfOI//TuI+zfTovFBXPNac2MmcPezaLchbWw5uKhoevPYQAu5E36gKUMnJw== Quan_Lam@mckinsey.com azureuser"
    - name: NETWORK_PLUGIN
      value: kubenet
    - name: NETWORK_PLUGIN_MODE
      value: ""
    - name: NETWORK_POLICY
      value: ""
    - name: VNET_SUBNET_ID
      value: /subscriptions/b5421ae3-32df-459b-8a71-52a6b1c9f6d0/resourceGroups/MC_rg1_primary_eastus/providers/Microsoft.Network/virtualNetworks/aks-vnet-31741753/subnets/aks-subnet
    - name: NODE_IDENTITIES
      value: /subscriptions/b5421ae3-32df-459b-8a71-52a6b1c9f6d0/resourcegroups/MC_rg1_primary_eastus/providers/Microsoft.ManagedIdentity/userAssignedIdentities/primary-agentpool
    # Azure client settings
    - name: ARM_SUBSCRIPTION_ID
      value: b5421ae3-32df-459b-8a71-52a6b1c9f6d0
    - name: LOCATION
      value: eastus
    - name: KUBELET_IDENTITY_CLIENT_ID
      value: ""
    - name: AZURE_NODE_RESOURCE_GROUP
      value: MC_rg1_primary_eastus
serviceAccount:
  name: karpenter-sa
  annotations:
    azure.workload.identity/client-id: e40bdb68-a40b-4267-8c39-9dfcda38786a
podLabels:
  azure.workload.identity/use: "true"
